# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.daemon                    = false
org.gradle.debug                     = false
org.gradle.jvmargs                   = -Xmx3G

# Plugins
fabric_loom_version                  = 1.6-SNAPSHOT
jetbrains_gradle_idea_ext_version    = 1.1.7
modmuss50_mod_publish_version        = 0.4.0
spongepowered_mixin_version          = 0.7-SNAPSHOT
spongepowered_vanilla_gradle_version = 0.2.1-SNAPSHOT

# Project
modrinthID				             = 9ON3zv6e
curseforgeID			             = 623560
projectSlug				             = log-begone

# Common
minecraft_version                    = 1.20.6

# NeoForge
loader_version_range                 = [2,)
mapping_channel                      = official
mapping_version                      = 1.20.6
minecraft_version_range              = [1.20.6, 1.21)
neo_gradle_userdev_version           = 7.0.116
neo_gradle_mixin_version             = 7.0.116
neo_version                          = 20.6.72-beta
neo_version_range                    = [20,)

# Fabric
fabric_version                       = 0.99.0+1.20.6
fabric_loader_version                = 0.15.11

# Mod options
group                                = mod.azure.logbegone
mod_name                             = Log Begone
mod_author                           = AzureDoom
mod_id                               = logbegone
mod_license                          = GPLv3
mod_description                      = I hate log spam, don't you?
mod_credits                          = AzureDoom, Bravarly
mod_logo                             = icon.png
mod_url                              = https://modrinth.com/mod/log-begone
mod_issues                           = https://github.com/AzureDoom/Log-Begone/issues
mod_sources                          = https://github.com/AzureDoom/Log-Begone
version                              = 1.0.0