modLoader="javafml"
loaderVersion="[46,)"
license="GPLv3"
[[mods]]
modId="logbegone"
version="${file.jarVersion}"
displayName="Log Begone"
logoFile="icon.png"
authors="AzureDoomC, Bravarly" 
description='''
I hate log spam, don't you?
'''
[[dependencies.forge]]
    modId="forge"
    mandatory=true 
    versionRange="[46.0.1,)" 
    ordering="NONE"
    side="BOTH"